on:
  workflow_dispatch:
name: Build and Release for Electron (Windows Only)
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        host: [x64]
        target: [x64]
        node: [20]
    name: Build Electron Package for Windows - host=${{ matrix.host }}, target=${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3
        with:
          msbuild-architecture: ${{ matrix.target }}

      - name: Install Electron
        run: npm install electron@22.2.1 --save-dev

      - name: Install dependencies
        run: npm install

      - name: Rebuild for Electron
        env:
          npm_config_target: 22.2.1                 # Electron version
          npm_config_arch: x64                      # Architecture
          npm_config_disturl: https://electronjs.org/headers
          npm_config_runtime: electron
          npm_config_build_from_source: true
        run: npm rebuild

      - name: Package Electron Build
        run: npm run pack

      - name: Release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
